# Generated by Django 4.2.5 on 2024-02-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryProfile',
        ),
    ]
