# Generated by Django 4.2.5 on 2024-02-12 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_deliveryregistrationrequests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryregistrationrequests',
            old_name='aadhar',
            new_name='aadhar_num',
        ),
        migrations.RenameField(
            model_name='deliveryregistrationrequests',
            old_name='license_num',
            new_name='lic_num',
        ),
        migrations.RenameField(
            model_name='deliveryregistrationrequests',
            old_name='RC',
            new_name='rc_num',
        ),
    ]
