# Generated by Django 4.2.5 on 2024-02-19 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_delete_deliveryprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=70)),
                ('country', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=70)),
                ('district', models.CharField(max_length=70)),
                ('pincode', models.CharField(max_length=70)),
                ('bank', models.CharField(max_length=70)),
                ('acc_num', models.CharField(max_length=70)),
                ('ifsc', models.CharField(max_length=70)),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.deliveryregistrationrequests')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
