# Generated by Django 4.2.5 on 2024-02-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_rename_aadhar_deliveryregistrationrequests_aadhar_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryregistrationrequests',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
