# Generated by Django 4.2 on 2024-03-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='picked_up_at',
        ),
        migrations.AddField(
            model_name='delivery',
            name='deliveryt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
