# Generated by Django 4.2 on 2024-03-20 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_rename_deliveryt_delivery_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivery',
            new_name='picked_up_at',
        ),
    ]
