# Generated by Django 4.2.5 on 2024-02-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='app2.cart'),
        ),
    ]
