# Generated by Django 4.2.5 on 2024-03-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
    ]
