# Generated by Django 4.2.5 on 2024-03-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_remove_order_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryregistrationrequests',
            name='lic_num',
            field=models.CharField(max_length=30),
        ),
    ]
