# Generated by Django 5.0.1 on 2024-02-06 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0013_rename_deliveryregistration_deliveryregistrationrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryregistrationrequest',
            old_name='idcard',
            new_name='id_num',
        ),
    ]
